version: "3.9"
services:
  api:
    build: ./api
    container_name: mvp_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api/app:/app/app:ro

  db:
    image: mysql:8.0
    container_name: mvp_db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer:4
    container_name: mvp_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
