-- Tabela base de jogos
CREATE TABLE IF NOT EXISTS games (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    received TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- FIFA
CREATE TABLE IF NOT EXISTS fifa (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_id BIGINT UNSIGNED NOT NULL,
    possession_percent FLOAT,
    goals_scored INT,
    goals_conceded INT,
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

-- LoL
CREATE TABLE IF NOT EXISTS lol (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_id BIGINT UNSIGNED NOT NULL,
    kills INT,
    deaths INT,
    assists INT,
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
